### PR TITLE
chore: enable autopublish

### LINKED ISSUE #92: Add [Exposed] to all interfaces
Needed for https://github.com/heycam/webidl/issues/365.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #92 also.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/selection-api/pull/107.html" title="Last updated on Jun 4, 2019, 7:16 AM UTC (003408e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/selection-api/107/aa3a8ff...003408e.html" title="Last updated on Jun 4, 2019, 7:16 AM UTC (003408e)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@siusin, seems this one also needs a Travis treatment 👩‍⚕️

**Review by siusin — APPROVED** [review]

**Comment by siusin** [comment]
@marcoscaceres 
I've disabled the Travis status check for this branch, and deleted the deprecated TravisCI Service on this repo. Maybe it requires a new commit to trigger the Travis check in the App :(

**Comment by marcoscaceres** [comment]
@siusin figure it out 🎉 One needs to go to "settings > branches > branch protection on gh-pages" and select "Require status checks to pass before merging". Then click on "TravisCI" to enable it.

**Comment by marcoscaceres** [comment]
@siusin no... I was wrong :( that didn't fix it. It seem to be missing from: https://travis-ci.com/account/repositories

**Comment by marcoscaceres** [comment]
Sorry, I mean "it seems to be missing"... argh.

**Comment by siusin** [comment]
@marcoscaceres 	TravisCI is already activated as GitHub App for this repo, and for all our other repos, we have "Require status checks..." disabled, not sure if we should make an exception here.

**Comment by marcoscaceres** [comment]
> we have "Require status checks..." disabled, not sure if we should make an exception here.

I think we need to enable it irrespectively, because we want enforce IPR checks and Travis (to make sure cross-references are not broken and markup remains valid).

**Pull request merged**
